### ISSUE TITLE
Can't get tomcat from the olnevhost mirror

### ISSUE THREAD

**Issue by hedb** [awslabs/aws-codedeploy-sample-tomcat#7]
http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz
=>
404

Here is the log from the CodeDeploy

Error CodeScriptFailed
Script Namescripts/install_dependencies
MessageScript at specified location: scripts/install_dependencies failed with exit code 8
Log TailLifecycleEvent - BeforeInstall
Script - scripts/install_dependencies
[stderr]tomcat7: unrecognized service
[stdout]/usr/bin/wget
[stderr]--2016-12-23 14:32:31--  http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz
[stderr]Resolving mirror.olnevhost.net (mirror.olnevhost.net)... 188.165.227.148
[stderr]Connecting to mirror.olnevhost.net (mirror.olnevhost.net)|188.165.227.148|:80... connected.
[stderr]HTTP request sent, awaiting response... 404 Not Found
[stderr]2016-12-23 14:32:33 ERROR 404: Not Found.
[stderr]

**Comment by gaohan137** [comment]
Hi there,

Are you consistently seeing this error? You can try manually use wget to connect to see if it works.

**Comment by hedb** [comment]
Does the link:
http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz
work for you?

In my local repo - i just advanced it to 73 - and it works OK.

**Comment by teknogeek0** [comment]
I've updated this to the most recent version (should be 75) and tested. Thanks for opening this issue! - Chris from AWS.
